// facts.json (Slovak, curated) + translations.json (ru/uk) -> public/handbook.js
//
// Translations are keyed by the Slovak string itself, not by a path, so re-ordering
// or renaming a card never orphans them and a reviewer can read the file as a list of
// pairs. A string with no translation falls back to Slovak, which is the same rule the
// interface catalogue uses.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const facts = JSON.parse(readFileSync(join(here, 'facts.json'), 'utf8'));
let tr = {};
try { tr = JSON.parse(readFileSync(join(here, 'translations.json'), 'utf8')); } catch { /* sk only */ }
const screen = JSON.parse(readFileSync(join(here, 'screen.json'), 'utf8'));

const all = Array.isArray(facts) ? facts : (facts.cards || facts.entries || []);
const byId = new Map(all.map((c) => [c.id, c]));
// screen.json decides what the screen shows and in what order; facts.json only knows
// what is true. An id that is in the facts but not in the order is deliberately left out.
const cards = screen.order.map((id) => {
  const c = byId.get(id);
  if (!c) throw new Error(`screen.json lists "${id}", which facts.json does not have`);
  return { ...c, summary_sk: c.summary_sk || screen.summaries_sk[id] };
});

// The icon names the app knows; anything else falls back to a document.
const ICONS = new Set(['campus', 'bus', 'food', 'book', 'card', 'mail', 'bed', 'globe', 'doc', 'schedule', 'user']);
const ICON_ALIAS = {
  transport: 'bus', doprava: 'bus', canteen: 'food', stravovanie: 'food', utensils: 'food',
  library: 'book', kniznica: 'book', isic: 'card', id: 'card', email: 'mail', teams: 'mail',
  mail: 'mail', accommodation: 'bed', ubytovanie: 'bed', internat: 'bed',
  building: 'campus', buildings: 'campus', areal: 'campus', orientation: 'campus', map: 'campus',
  exchange: 'globe', erasmus: 'globe', compass: 'globe', study: 'schedule', studium: 'schedule',
  calendar: 'schedule', monitor: 'doc', flask: 'doc', poll: 'doc', phone: 'user', users: 'user',
};

let missing = 0;
const TARGETS = ['ru', 'uk', 'en'];

function ml(sk) {
  const s = String(sk ?? '').trim();
  if (!s) return undefined;
  const t = tr[s] || {};
  const out = { sk: s };
  TARGETS.forEach((lang) => {
    if (!t[lang]) missing += 1;
    out[lang] = t[lang] || s;   // a missing translation falls back to Slovak, never to a key
  });
  return out;
}

const out = cards.map((c) => {
  const hint = String(c.icon || c.icon_hint || '').toLowerCase();
  const icon = ICONS.has(hint) ? hint : (ICON_ALIAS[hint] || 'doc');
  // A card wears a photograph when one exists for it, and falls back to its icon.
  const photo = `photos/uni/${c.id}.webp`;
  const hasPhoto = existsSync(join(here, '..', '..', 'public', photo));
  return {
    id: c.id,
    icon,
    ...(hasPhoto ? { photo: `/${photo}` } : {}),
    title: ml(c.title_sk || c.title),
    summary: ml(c.summary_sk || c.summary),
    items: (c.items || []).map((i) => {
      const item = { label: ml(i.label_sk || i.label), value: ml(i.value_sk || i.value) };
      if (i.url) item.url = i.url;
      if (i.copy) item.copy = true;
      return item;
    }),
    source: c.source_url || c.source,
  };
});

const checked = (Array.isArray(facts) ? cards[0]?.checked : facts.checked) || cards[0]?.checked || '';
if (!checked) throw new Error('facts.json carries no `checked` date');
const header = `// Student handbook: a curated snapshot of the practical pages at sp.euba.sk.
//
// Facts, not paragraphs, and our own wording with a link back to the source — the pages
// are static and tiny, so a runtime parser would be a moving part for nothing.
// GENERATED by scripts/handbook/build.mjs from facts.json + translations.json.
// Edit those, not this file, then re-run: node scripts/handbook/build.mjs
export const HANDBOOK_CHECKED = ${JSON.stringify(checked)};
export const HANDBOOK = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(join(here, '..', '..', 'public', 'handbook.js'), header);
const facts_n = out.reduce((a, c) => a + c.items.length, 0);
console.log(`public/handbook.js: ${out.length} cards, ${facts_n} facts, ${missing} missing translations (sk fallback)`);
